config/routes.rb
Rails.application.routes.draw do
  root "dancers#index"

  resources :dancer_partners, only: [:new, :create, :show]
  resources :international_couples, only: [:index]
  resources :devoted_dancers, only: [:index]
  resources :dancers_most_competitions, only: [:index]
  resources :dancers_most_divisions, only: [:index]
  resources :dancers_most_age_sections, only: [:index]
  resources :avg_yearly_couple_competitions, only: [:index]
  resources :country_most_couples_competitions, only: [:index]
  resources :competitions_most_earnings, only: [:index]
  resources :dancer_slowest_divisions, only: [:index]
  resources :data, only: [:index]
  resources :couples
  resources :dancers
  resources :entries
  resources :participants
  resources :competitions
  resources :age_sections
  resources :divisions
end

app/models/competition.rb
class Competition < ApplicationRecord
  has_many :entries
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: [:show, :edit, :update, :destroy]

  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(competition_params)

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: 'Competition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:name, :date, :country, :price, :currency, :max_couples_on_floor)
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.erb
<%= form_with(model: competition, local: true) do |form| %>
  <% if competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% competition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :competition_name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :competition_date %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :competition_country %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :competition_price %>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.text_field :currency, id: :competition_currency %>
  </div>

  <div class="field">
    <%= form.label :max_couples_on_floor %>
    <%= form.number_field :max_couples_on_floor, id: :competition_max_couples_on_floor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<h1>Editing Competition</h1>

<%= render 'form', competition: @competition %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>

app/views/competitions/index.html.erb
<%= render 'shared/header' %>

<p id="notice"><%= notice %></p>

<h1>Competitions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Country</th>
      <th>Price</th>
      <th>Currency</th>
      <th>Max couples on floor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @competitions.each do |competition| %>
      <tr>
        <td><%= competition.name %></td>
        <td><%= competition.date %></td>
        <td><%= competition.country %></td>
        <td><%= competition.price %></td>
        <td><%= competition.currency %></td>
        <td><%= competition.max_couples_on_floor %></td>
        <td><%= link_to 'Show', competition %></td>
        <td><%= link_to 'Edit', edit_competition_path(competition) %></td>
        <td><%= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Competition', new_competition_path %>

app/views/competitions/new.html.erb
<h1>New Competition</h1>

<%= render 'form', competition: @competition %>

<%= link_to 'Back', competitions_path %>

app/views/competitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @competition.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @competition.date %>
</p>

<p>
  <strong>Country:</strong>
  <%= @competition.country %>
</p>

<p>
  <strong>Price:</strong>
  <%= @competition.price %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @competition.currency %>
</p>

<p>
  <strong>Max couples on floor:</strong>
  <%= @competition.max_couples_on_floor %>
</p>

<%= link_to 'Edit', edit_competition_path(@competition) %> |
<%= link_to 'Back', competitions_path %>