config/routes.rb
Rails.application.routes.draw do
  root "dancers#index"

  resources :dancer_partners, only: [:new, :create, :show]
  resources :international_couples, only: [:index]
  resources :devoted_dancers, only: [:index]
  resources :dancers_most_competitions, only: [:index]
  resources :dancers_most_divisions, only: [:index]
  resources :dancers_most_age_sections, only: [:index]
  resources :avg_yearly_couple_competitions, only: [:index]
  resources :country_most_couples_competitions, only: [:index]
  resources :competitions_most_earnings, only: [:index]
  resources :dancer_slowest_divisions, only: [:index]
  resources :data, only: [:index]
  resources :couples
  resources :dancers
  resources :entries
  resources :participants
  resources :competitions
  resources :age_sections
  resources :divisions
end

app/models/division.rb
# Class that shows the division in which a dancer activates
# name examples: Professional, General
class Division < ApplicationRecord
  has_many :entries

  validates :name,  presence: true, length: { maximum: 50 }
  validates :ranking,  uniqueness: true
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_action :set_division, only: [:show, :edit, :update, :destroy]

  # GET /divisions
  # GET /divisions.json
  def index
    @divisions = Division.all
  end

  # GET /divisions/1
  # GET /divisions/1.json
  def show
  end

  # GET /divisions/new
  def new
    @division = Division.new
  end

  # GET /divisions/1/edit
  def edit
  end

  # POST /divisions
  # POST /divisions.json
  def create
    @division = Division.new(division_params)

    respond_to do |format|
      if @division.save
        format.html { redirect_to @division, notice: 'Division was successfully created.' }
        format.json { render :show, status: :created, location: @division }
      else
        format.html { render :new }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divisions/1
  # PATCH/PUT /divisions/1.json
  def update
    respond_to do |format|
      if @division.update(division_params)
        format.html { redirect_to @division, notice: 'Division was successfully updated.' }
        format.json { render :show, status: :ok, location: @division }
      else
        format.html { render :edit }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1
  # DELETE /divisions/1.json
  def destroy
    @division.destroy
    respond_to do |format|
      format.html { redirect_to divisions_url, notice: 'Division was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_division
      @division = Division.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def division_params
      params.require(:division).permit(:name, :ranking)
    end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_form.html.erb
<%= form_with(model: division, local: true) do |form| %>
  <% if division.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(division.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
      <% division.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :division_name %>
  </div>

  <div class="field">
    <%= form.label :ranking %>
    <%= form.text_field :ranking, id: :division_ranking %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/divisions/edit.html.erb
<h1>Editing Division</h1>

<%= render 'form', division: @division %>

<%= link_to 'Show', @division %> |
<%= link_to 'Back', divisions_path %>

app/views/divisions/index.html.erb
<%= render 'shared/header' %>

<p id="notice"><%= notice %></p>

<h1>Divisions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ranking</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @divisions.each do |division| %>
      <tr>
        <td><%= division.name %></td>
        <td><%= division.ranking %></td>
        <td><%= link_to 'Show', division %></td>
        <td><%= link_to 'Edit', edit_division_path(division) %></td>
        <td><%= link_to 'Destroy', division, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Division', new_division_path %>

app/views/divisions/new.html.erb
<h1>New Division</h1>

<%= render 'form', division: @division %>

<%= link_to 'Back', divisions_path %>

app/views/divisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @division.name %>
</p>

<p>
  <strong>Ranking:</strong>
  <%= @division.ranking %>
</p>

<%= link_to 'Edit', edit_division_path(@division) %> |
<%= link_to 'Back', divisions_path %>