config/routes.rb
Rails.application.routes.draw do
  root "dancers#index"

  resources :dancer_partners, only: [:new, :create, :show]
  resources :international_couples, only: [:index]
  resources :devoted_dancers, only: [:index]
  resources :dancers_most_competitions, only: [:index]
  resources :dancers_most_divisions, only: [:index]
  resources :dancers_most_age_sections, only: [:index]
  resources :avg_yearly_couple_competitions, only: [:index]
  resources :country_most_couples_competitions, only: [:index]
  resources :competitions_most_earnings, only: [:index]
  resources :dancer_slowest_divisions, only: [:index]
  resources :data, only: [:index]
  resources :couples
  resources :dancers
  resources :entries
  resources :participants
  resources :competitions
  resources :age_sections
  resources :divisions
end

app/models/age_section.rb
class AgeSection < ApplicationRecord
  has_many :entries
end

app/controllers/age_sections_controller.rb
class AgeSectionsController < ApplicationController
  before_action :set_age_section, only: [:show, :edit, :update, :destroy]

  # GET /age_sections
  # GET /age_sections.json
  def index
    @age_sections = AgeSection.all
  end

  # GET /age_sections/1
  # GET /age_sections/1.json
  def show
  end

  # GET /age_sections/new
  def new
    @age_section = AgeSection.new
  end

  # GET /age_sections/1/edit
  def edit
  end

  # POST /age_sections
  # POST /age_sections.json
  def create
    @age_section = AgeSection.new(age_section_params)

    respond_to do |format|
      if @age_section.save
        format.html { redirect_to @age_section, notice: 'AgeSection was successfully created.' }
        format.json { render :show, status: :created, location: @age_section }
      else
        format.html { render :new }
        format.json { render json: @age_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /age_sections/1
  # PATCH/PUT /age_sections/1.json
  def update
    respond_to do |format|
      if @age_section.update(age_section_params)
        format.html { redirect_to @age_section, notice: 'AgeSection was successfully updated.' }
        format.json { render :show, status: :ok, location: @age_section }
      else
        format.html { render :edit }
        format.json { render json: @age_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /age_sections/1
  # DELETE /age_sections/1.json
  def destroy
    @age_section.destroy
    respond_to do |format|
      format.html { redirect_to age_sections_url, notice: 'AgeSection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_age_section
      @age_section = AgeSection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def age_section_params
      params.require(:age_section).permit(:name)
    end
end

app/helpers/agesections_helper.rb
module AgesectionsHelper
end

app/views/age_sections/_form.html.erb
<%= form_with(model: age_section, local: true) do |form| %>
  <% if age_section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(age_section.errors.count, "error") %> prohibited this age_section from being saved:</h2>

      <ul>
      <% age_section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :age_section_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/age_sections/edit.html.erb
<h1>Editing Agesection</h1>

<%= render 'form', age_section: @age_section %>

<%= link_to 'Show', @age_section %> |
<%= link_to 'Back', age_sections_path %>

app/views/age_sections/index.html.erb
<%= render 'shared/header' %>

<p id="notice"><%= notice %></p>

<h1>Age sections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @age_sections.each do |age_section| %>
      <tr>
        <td><%= age_section.name %></td>
        <td><%= link_to 'Show', age_section %></td>
        <td><%= link_to 'Edit', edit_age_section_path(age_section) %></td>
        <td><%= link_to 'Destroy', age_section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Age section', new_age_section_path %>

app/views/age_sections/new.html.erb
<h1>New Agesection</h1>

<%= render 'form', age_section: @age_section %>

<%= link_to 'Back', age_sections_path %>

app/views/age_sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @age_section.name %>
</p>

<%= link_to 'Edit', edit_age_section_path(@age_section) %> |
<%= link_to 'Back', age_sections_path %>