config/routes.rb
Rails.application.routes.draw do
  root "dancers#index"

  resources :dancer_partners, only: [:new, :create, :show]
  resources :international_couples, only: [:index]
  resources :devoted_dancers, only: [:index]
  resources :dancers_most_competitions, only: [:index]
  resources :dancers_most_divisions, only: [:index]
  resources :dancers_most_age_sections, only: [:index]
  resources :avg_yearly_couple_competitions, only: [:index]
  resources :country_most_couples_competitions, only: [:index]
  resources :competitions_most_earnings, only: [:index]
  resources :dancer_slowest_divisions, only: [:index]
  resources :data, only: [:index]
  resources :couples
  resources :dancers
  resources :entries
  resources :participants
  resources :competitions
  resources :age_sections
  resources :divisions
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  def index
  end
end

app/helpers/data_helper.rb
module DataHelper

end

app/views/data/dancer_with_most_competitions.html.erb
<%= render 'shared/header' %>

</br>
</br>
<%= @title %>
</br>
</br>

<% @dancers_most_entries.each do |dancer_id|%>
  <p>
    <%= Dancer.find(dancer_id).name %>
  </p>
  <p>
    was in couples:
    <% Couple.where(boy_id: dancer_id).each do |couple| %>
      <%= couple.id%>
    <% end %>
    <% Couple.where(girl_id: dancer_id).each do |couple| %>
      <%= couple.id%>
    <% end %>
  </p>
  <p>
    has <%= @nr_entries_dancer[dancer_id] %> entries in competitions
  </p>
<% end %>

app/views/data/dancers_in_one_couple.html.erb
<%= render 'shared/header' %>

</br>
<%= @title %>
</br>

<% @lst_dancers.each do |dancer| %>
  <li>
    <p>
      id: <%= dancer.id %>
    </p>
  <%= dancer.name %>
  </li>
<% end %>

app/views/data/index.html.erb
<%= render 'shared/header' %>

<h1>Data</h1>

<%= link_to 'All partners of a dancer', new_dancer_partner_path %>
</br>

<%= link_to 'Couples with dancers from different countries', international_couples_path %>
</br>

<%= link_to "Dancers that have been in a couple with only one dancer", devoted_dancers_path %>
</br>
<%= link_to "Dancers with most competitions", dancers_most_competitions_url %>
</br>
<%= link_to "Dancers with most divisions", dancers_most_divisions_url %>
</br>
<%= link_to "Dancers with most age sections", dancers_most_age_sections_url %>
</br>
<%= link_to "Dancers with slowest journey through divisions", dancer_slowest_divisions_url %>
</br>
<%= link_to "Average yearly competitions per couple", avg_yearly_couple_competitions_url %>
</br>
<%= link_to "Countries with most couples at competitions", country_most_couples_competitions_url %>
</br>
<%= link_to "Competitions with most earnings", competitions_most_earnings_url %>

app/views/data/query3.html.erb
<%= render 'shared/header' %>

</br>
<%= @query3_title %>
</br>

<% @lstDancers.each do |d| %>
  <li><%= d.id %></li>
<% end %>